spring.application.name=Secure Storage Vault

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/VaultDB

app.share.base-url=${APP_SHARE_BASE_URL:http://localhost:8080}
app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost,http://localhost:5173,http://localhost:5174,https://vaultfrontend.z29.web.core.windows.net/}

# DB credentials
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=admin
spring.security.user.password=1234

# Storage Provider (local or s3)
storage.provider=s3

# JWT Configuration
jwt.secret=${JWT_SECRET}

# AWS S3 Configuration
aws.s3.bucket=vault-db-file-bucket
aws.region=ap-south-1
aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}


# Multipart Configuration
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB