name: Build and Deploy to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/vault-backend
          # Change to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          docker build -t $IMAGE_ID:latest -t $IMAGE_ID:${{ github.sha }} ./backend
          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:${{ github.sha }}

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-and-push-backend
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: ${{ secrets.CONTAINER_APP_NAME }}
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          imageToDeploy: ghcr.io/${{ github.repository_owner }}/vault-backend:latest
          registryUrl: ghcr.io
          registryUsername: ${{ github.actor }}
          registryPassword: ${{ secrets.GITHUB_TOKEN }}
          environmentVariables: |
            DB_HOST=${{ secrets.DB_HOST }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            ALLOWED_ORIGINS=https://${{ secrets.STORAGE_ACCOUNT_NAME }}.z29.web.core.windows.net

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} npm run build

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Azure Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --auth-mode key --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} -d '$web' -s frontend/dist --overwrite
